import { AiFillWindows } from "react-icons/ai";
import { FaPlaystation, FaXbox } from "react-icons/fa";
import { SiNintendoswitch } from "react-icons/si"

export function applyDiscount(price: string, discount: string) {
  const priceNumber = parseFloat(price.replace('R$ ', '').replace(',', '.'));
  const discountNumber = parseFloat(discount.replace('%', ''));
  const newValue = priceNumber * (1 - discountNumber / 100);
  return `R$ ${newValue.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function calculateValueReviews(positiveReviews: string): string {
  const percentage = parseInt(positiveReviews.replace('%', ''));

  if (percentage < 25) {
    return 'Negativas'; 
  } else if (percentage < 50) {
    return 'Neutras';
  } else if (percentage < 75) {
    return 'Ligeiramente positivas';
  } else if (percentage < 95) {
    return 'Muito positivas';
  } else {
    return 'Extremamente positivas';
  }
}

const base = [
  {
    imageUrl: '',
    alt: '',
    name: '',
    info: '',
    devices: '',
    description: '',
    categories: '',
    price: '',
    discount: '',
  }
]

export const carouselImages = [
  "/images/carousel/deadspace.jpg",
  "/images/carousel/returnal.jpg",
  "/images/carousel/csgo.jpg",
  "/images/carousel/devilmaycry.jpg",
  "/images/carousel/poefire.jpg"
];

export const carouselText = [
  "O clássico de terror de sobrevivência e ficção científica está de volta, totalmente reformulado para oferecer uma experiência ainda mais imersiva.",
  "Enfrente desafios roguelike. Encare inimigos em lutas de bullet hell. Divida sua jornada em Returnal™ com outro jogador.",
  "CS:GO é um FPS da Valve disputado entre duas equipes. Elas se revezam entre terroristas e contra terroristas, os terroristas armam a bomba enquanto o outro time protege os sites, locais onde os explosivos devem ser plantados.",
  "Devil May Cry 5 é o novo jogo desta lendária série de ação e junta a sua clássica ação cheia de adrenalina e personagens sobrenaturais peculiares.",
  "Você é um exilado, lutando para sobreviver no continente sombrio de Wraeclast, enquanto luta para ganhar o poder que permitirá que você se vingue daqueles que o injustiçaram."
];

export const carouselPrice = [
  "R$ 249,90",
  "R$ 249,90",
  "Gratuito",
  "R$ 252,00",
  "Gratuito"
];

export const purchaseButton = [
  "Compre agora",
  "Compre agora",
  "Baixe agora",
  "Compre agora",
  "Baixe agora"
];

export const carouselTitle = [
  "Dead Space Remake",
  "Returnal",
  "Counter Strike: Global Offensive",
  "Devil May Cry 5",
  "Path of Exile"
];

export const carouselWishlist = [
  "+ Lista de desejos",
  "+ Lista de desejos",
  "",
  "+ Lista de desejos",
  ""
]

export const mainSlider = [
  {
    imageUrl: "/images/mainSlider/deadspaceSlider.jpg",
    alt: "Dead Space Remake",
    name: "Dead Space Remake",
    info: '',
    devices: '',
    description: "O clássico de terror de sobrevivência e ficção científica está de volta, totalmente reformulado para oferecer uma experiência ainda mais imersiva.",
    categories: '',
    price: "R$ 249,90",
    discount: '',
    purchaseButton: "Compre agora",
    wishlist: "+ Lista de desejos"
  },
  {
    imageUrl: "/images/mainSlider/returnalSlider.jpg",
    alt: "Returnal",
    name: "Returnal",
    info: '',
    devices: '',
    description: "Enfrente desafios roguelike. Encare inimigos em lutas de bullet hell. Divida sua jornada em Returnal™ com outro jogador.",
    categories: '',
    price: "R$ 249,90",
    discount: '',
    purchaseButton: "Compre agora",
    wishlist: "+ Lista de desejos"
  },
  {
    imageUrl: "/images/mainSlider/thelast1Slider.jpg",
    alt: "The Last of Us 1",
    name: "The last of Us - Part 1",
    info: '',
    devices: '',
    description: "Conheça a história emocionante e os personagens inesquecíveis de The Last of Us, vencedor de mais de 200 prêmios de Jogo do Ano.",
    categories: '',
    price: "R$ 249,99",
    discount: '',
    purchaseButton: "Jogar",
    wishlist: "Gratuito p/jogar"
  },
  {
    imageUrl: "/images/mainSlider/devilmaycrySlider.jpg",
    alt: "Devil May Cry 5",
    name: "Devil May Cry 5",
    info: '',
    devices: '',
    description: "Devil May Cry 5 é o novo jogo desta lendária série de ação e junta a sua clássica ação cheia de adrenalina e personagens sobrenaturais peculiares.",
    categories: '',
    price: "R$ 252,00",
    discount: '',
    purchaseButton: "Compre agora",
    wishlist: "+ Lista de desejos"
  },
  {
    imageUrl: "/images/mainSlider/poeSlider.jpg",
    alt: "Path of Exile",
    name: "Path of Exile",
    info: '',
    devices: '',
    description: "Você é um exilado, lutando para sobreviver no continente sombrio de Wraeclast, enquanto luta para ganhar o poder que permitirá que você se vingue daqueles que o injustiçaram.",
    categories: '',
    price: "Gratuito",
    discount: '',
    purchaseButton: "Jogar",
    wishlist: "Gratuito p/jogar"
  }
];

export const destaqueDescontos = [
  {
    imageUrl: "/images/destaques/thelast1.jpg",
    alt: 'Imagem do jogo The Last of Us 1',
    name: "The Last of Us. Part I",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 249,99',
    discount: '15%',
  },
  {
    imageUrl: "/images/destaques/thelast2.jpg",
    alt: 'Imagem do jogo The Last of Us 2',
    name: "The Last of Us. Part II",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 199,99',
    discount: '30%',
  },
  {
    imageUrl: "/images/destaques/resident.jpg",
    alt: 'Imagem do jogo Resident Evil 4',
    name: "Resident Evil 4",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 249,00',
    discount: '45%',
  },
  {
    imageUrl: "/images/destaques/hogwartsDeluxe.jpg",
    alt: 'Imagem do jogo Hogwarts Legacy',
    name: "Hogwarts Legacy - Deluxe",
    info: 'Edição',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 249,99',
    discount: '20%',
  },
  {
    imageUrl: "/images/destaques/subnauticabelow.jpg",
    alt: 'Imagem do jogo Subnautica Below Zero',
    name: "Subnautica Below Zero",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 155,89',
    discount: '10%',
  },
  {
    imageUrl: "/images/destaques/assassinscreed.jpg",
    alt: 'Imagem do jogo Assassins Creed Valhalla',
    name: "Assassin's Creed Valhalla",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 199,99',
    discount: '67%',
  },
  {
    imageUrl: "/images/destaques/residentevilvillage.jpg",
    alt: 'Imagem do jogo Resident Evil Village',
    name: "Resident Evil Village",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 139,90',
    discount: '50%',
  },
  {
    imageUrl: "/images/destaques/gtav.jpg",
    alt: 'Imagem do jogo Grand Theft Auto V',
    name: "Grand Theft Auto V",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 99,99',
    discount: '65%',
  },
  {
    imageUrl: "/images/destaques/borderlands3.jpg",
    alt: 'Imagem do jogo Borderlands 3',
    name: "Borderlands 3",
    info: 'Jogo base',
    devices: '',
    description: '',
    categories: '',
    price: 'R$ 119,90',
    discount: '25%',
  },
];

export const categories = [
  {
    imageUrl: '/images/categorias/action.jpg',
    categorie: 'Ação',
  },
  {
    imageUrl: '/images/categorias/survival.jpg',
    categorie: 'Sobrevivência',
  },
  {
    imageUrl: '/images/categorias/dungeon.jpg',
    categorie: 'Roguelike',
  },
  {
    imageUrl: '/images/categorias/strategy2.jpg',
    categorie: 'Estratégia',
  },
  {
    imageUrl: '/images/categorias/horror2.jpg',
    categorie: 'Terror',
  },
  {
    imageUrl: '/images/categorias/coop.jpg',
    categorie: 'Cooperativo',
  },
  {
    imageUrl: '/images/categorias/racingGame.jpg',
    categorie: 'Corrida',
  },
  {
    imageUrl: '/images/categorias/sports2.jpg',
    categorie: 'Esportes',
  },
  {
    imageUrl: '/images/categorias/fight2.jpg',
    categorie: 'Luta',
  },
  {
    imageUrl: '/images/categorias/simulator2.jpg',
    categorie: 'Simulação',
  },
  {
    imageUrl: '/images/categorias/futuristic2.jpg',
    categorie: 'Futurista',
  },
  {
    imageUrl: '/images/categorias/indie2.jpg',
    categorie: 'Indie',
  },
];

export const novidadesPopulares = [
  {
    imageUrl: "/images/populares/theforest.jpg",
    alt: 'Imagem do jogo Sons of The Forest',
    name: "Sons of The Forest",
    info: 'Jogo base',
    devices: '',
    description: "Enviado para encontrar um bilionário desaparecido em uma ilha remota, você se encontra em uma paisagem infernal infestada de canibais. Crie, construa e lute para sobreviver, sozinho ou com amigos, neste novo e assustador simulador de horror de sobrevivência em mundo aberto.",
    categories: '',
    price: 'R$ 88,99',
    discount: '',
  },
  {
    imageUrl: "/images/populares/fifa23.jpg",
    alt: 'Imagem do jogo Fifa 2023',
    name: "EA™ FIFA 23",
    info: 'Jogo base',
    devices: '',
    description: "FIFA 23 traz o Jogo de Todo Mundo aos gramados com a tecnologia HyperMotion2, a FIFA World Cup™ masculina e feminina (lançamento durante a temporada), times femininos, recursos de crossplay* e muito mais.",
    categories: '',
    price: "R$ 299,00",
    discount: '',
  },
  {
    imageUrl: "/images/populares/vampiresurvivors.jpg",
    alt: 'Imagem do jogo Vampire Survivors',
    name: "Vampire Survivors",
    info: '',
    devices: '',
    description: "Acabe com milhares de criaturas noturnas e sobreviva até o amanhecer! Vampire Survivors é um jogo casual de terror gótico com elementos roguelite onde suas escolhas podem fazer você crescer rapidamente e aniquilar os milhares de monstros que aparecem pelo caminho.",
    categories: '',
    price: "R$ 12,99",
    discount: '',
  },
  {
    imageUrl: "/images/populares/lightfall.jpg",
    alt: 'Imagem da expansão Destiny 2 - Lightfall',
    name: "Destiny 2 - Lightfall",
    info: 'Expansão',
    devices: '',
    description: "Numa cidade netuniana sitiada, encontre forças nos seus companheiros Guardiões quando o fim de todas as coisas se aproximar — a Testemunha chegou. Equipe-se com novas recompensas e desbloqueie poderes inéditos da Treva para triunfar no inesquecível modo Lendário de A Queda da Luz.",
    categories: '',
    price: "R$ 149,99",
    discount: '',
  },
  {
    imageUrl: "/images/populares/atomic.jpg",
    alt: 'Imagem do jogo Atomic Heart',
    name: "Atomic Heart",
    info: 'Jogo base',
    devices: '',
    description: "Em um mundo utópico, insano e deslumbrante, trave batalhas explosivas. Adapte seu estilo de luta a cada novo oponente, tire vantagem do espaço e aprimore seus equipamentos para completar a missão. O preço da verdade será pago com sangue.",
    categories: '',
    price: "R$ 199,90",
    discount: '',
  },
  {
    imageUrl: "/images/populares/cod.jpg",
    alt: 'Imagem do jogo Call of Duty®: Modern Warfare® II',
    name: "Call of Duty: MW II",
    info: 'Jogo base',
    devices: '',
    description: "O Call of Duty®: Modern Warfare® II coloca os jogadores dentro de um conflito global sem precedentes que conta com o retorno dos Operadores icônicos da Força-Tarefa 141.",
    categories: '',
    price: "R$ 299,90",
    discount: '',
  },
  {
    imageUrl: "/images/populares/valheim1920.jpg",
    alt: 'Imagem do jogo Valheim e sua atualização Mistlands',
    name: "Valheim - Mistlands",
    info: 'Grande atualização',
    devices: '',
    description: "Um brutal jogo de exploração e sobrevivência para 1 a 10 jogadores, ambientado em um purgatório gerado de forma procedural, inspirado na cultura viking. Batalhe, construa e conquiste glória em uma saga digna da benção de Odin!",
    categories: '',
    price: "R$ 37,99",
    discount: '',
  },
  {
    imageUrl: "/images/populares/hogwarts.jpg",
    alt: 'Imagem do jogo Hogwarts Legacy',
    name: "Hogwarts Legacy",
    info: 'Jogo base',
    devices: '',
    description: "Hogwarts Legacy é um RPG de ação imersivo de mundo aberto. Agora você pode assumir o controle da ação e estar no centro de sua própria aventura no mundo bruxo.",
    categories: '',
    price: "R$ 249,99",
    discount: '',
  },
];

export const jogosAguardados = [
  {
    imageUrl: "/images/aguardados/frostpunk.jpg",
    alt: 'Imagem do jogo Frostpunk 2',
    name: "Frostpunk 2",
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: "Frostpunk 2 é a sequência do aclamado jogo de sobrevivência em sociedade indicado ao BAFTA. A era do vapor já passou e agora o petróleo é tido como a mais nova salvação da humanidade. No entanto, com novas ameaças a caminho, o futuro da cidade parece ainda mais sombrio do que antes.",
    categories: ['Estratégia', 'Sobrevivência', 'Construção de Cidades'],
    price: 'R$ 199,99',
    discount: '',
    releaseDate: 'Em breve',
    developer: '11 bit studios',
  },
  {
    imageUrl: "/images/aguardados/diabloo.jpg",
    alt: 'Imagem do jogo Diablo IV',
    name: "Diablo IV",
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: "Diablo IV é um RPG de ação em desenvolvimento pela Blizzard Entertainment, o quarto título da série Diablo. Em 1.º de novembro de 2019, durante a Blizzcon, o jogo foi oficialmente anunciado para PC, PlayStation 4 e Xbox One.",
    categories: ['Ação', 'Hack and Slash', 'RPG', 'Ficção'],
    price: 'R$ 439,90',
    discount: '',
    releaseDate: '10/mar./2023',
    developer: 'Blizzard Entertainment',
  },
  {
    imageUrl: "/images/aguardados/outlast.jpg",
    alt: 'Imagem do jogo The Outlast Trials',
    name: "The Outlast Trials",
    info: '',
    devices: [<AiFillWindows />],
    description: "Red Barrels convida você a experimentar o terror entorpecente, desta vez com amigos. Quer você passe pelos testes sozinho ou em equipe, se sobreviver o suficiente e concluir a terapia, Murkoff ficará feliz em deixá-lo partir ... mas você será o mesmo?",
    categories: ['Terror', 'Primeira Pessoa', 'Cooperativo', 'Ação'],
    price: 'R$: Não Divulgado',
    discount: '',
    releaseDate: 'Em breve',
    developer: 'Red Barrels',
  },
  {
    imageUrl: "/images/aguardados/starfield.jpg",
    alt: 'Imagem do jogo Starfield',
    name: "Starfield",
    info: '',
    devices: [<AiFillWindows />, <FaXbox />],
    description: "Starfield é um futuro jogo eletrônico de RPG de ação e ficção em desenvolvimento pela Bethesda Game Studios, publicado pela Bethesda Softworks e distribuído pela Microsoft.",
    categories: ['Ação', 'Aventura', 'RPG', 'Futurista'],
    price: 'R$: Não Divulgado',
    discount: '',
    releaseDate: '2023',
    developer: 'Bethesda',
  },
  {
    imageUrl: "/images/aguardados/starwars.jpg",
    alt: 'Imagem do jogo Star Wars Jedi: Survivor',
    name: "Star Wars Jedi: Survivor",
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: "Star Wars Jedi: Survivor é um próximo jogo de ação e aventura desenvolvido pela Respawn Entertainment e publicado pela Electronic Arts. Uma sequência de Star Wars Jedi: Fallen Order, está programada para ser lançada no PlayStation 5, Windows e Xbox Series X/S.",
    categories: ['Ação', 'Aventura', 'Souslike', 'Mundo Aberto'],
    price: 'R$ 339,00',
    discount: '',
    releaseDate: '28/abr./2023',
    developer: 'Electronic Arts',
  },
  {
    imageUrl: "/images/aguardados/zelda.jpg",
    alt: 'The Legend of Zelda: Tears of the Kingdom',
    name: "Zelda: Tears of the Kingdom",
    info: '',
    devices: [<SiNintendoswitch />],
    description: "The Legend of Zelda: Tears of the Kingdom é um futuro jogo eletrônico de ação-aventura desenvolvido e publicado pela Nintendo. Está programado para ser lançado em 12 de maio de 2023 para Nintendo Switch. Faz parte da série The Legend of Zelda, e é a sequência de The Legend of Zelda: Breath of the Wild.",
    categories: ['Ação', 'Aventura', 'Switch', 'Exploração'],
    price: 'R$ 357,99',
    discount: '',
    releaseDate: '12/maio/2023',
    developer: 'Nintendo',
  },
  {
    imageUrl: "/images/aguardados/finalfantasy.jpg",
    alt: 'Imagem do jogo Final Fantasy XVI',
    name: "Final Fantasy XVI",
    info: '',
    devices: [<FaPlaystation />],
    description: "Final Fantasy XVI é um jogo eletrônico de RPG de ação desenvolvido e publicado pela Square Enix. É o décimo sexto título principal da série Final Fantasy e está programado para ser lançado em 22 de junho de 2023 para PlayStation 5. Está sendo dirigido por Hiroshi Takai e produzido por Naoki Yoshida.",
    categories: ['Ação', 'Aventura', 'RPG', 'Hack and Slash'],
    price: 'R$ 349,90',
    discount: '',
    releaseDate: '22/jun./2023',
    developer: 'Square Enix',
  },
  {
    imageUrl: "/images/aguardados/remnant2.jpg",
    alt: 'Imagem do jogo Remnant 2',
    name: "Remnant 2",
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: "Em Remnant 2, os sobreviventes da humanidade têm que enfrentar novas e mortais criaturas, além de chefes impossíveis em mundos aterrorizantes. Jogue por conta própria ou em modo cooperativo com dois outros amigos e explore as profundezas do desconhecido para impedir que o mal destrua a própria realidade.",
    categories: ['Ação', 'Aventura', 'RPG', 'Souslike'],
    price: 'R$: Não divulgado',
    discount: '',
    releaseDate: 'Em breve',
    developer: 'Gunfire Games',
  },
];

export const atualizadosRecentemente = [
  {
    imageUrl: '/images/atualizados/pathfinder.jpg',
    alt: 'Imagem do jogo Pathfinder: Wrath of the Righteous',
    name: 'Pathfinder: Wrath of the Righteous',
    info: 'Grande atualização',
    devices: '',
    description: 'Uma atualização 2.1.0u está ativa. O DLC Last Sarkorians também está disponível. Hora de aprender a nova armadilha.',
    categories: '',
    price: 'R$: 149,99',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/callisto.jpg',
    alt: 'Imagem do jogo The Callisto Protocol',
    name: 'The Callisto Protocol',
    info: 'Grande atualização',
    devices: '',
    description: 'Uma visão desafiadora da experiência de terror e sobrevivência do Protocolo Callisto, destinada a levá-lo aos seus limites, o modo Hardcore não é para os fracos de coração.',
    categories: '',
    price: 'R$: 249,00',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/rainbowsixsiege.png',
    alt: 'Imagem do jogo Tom Clancy\'s Rainbow Six® Siege',
    name: 'Tom Clancy\'s Rainbow Six® Siege',
    info: 'Grande atualização',
    devices: '',
    description: 'Comemore o início do 8º ano de Rainbow Six Siege com a melhor oferta de passes de batalha que você pode obter o ano todo. O Passe do Ano 8 vem com todos os quatro Passes de Batalha do Ano 8, 4 novos Operadores e muito mais.',
    categories: '',
    price: 'R$: 59,99',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/eldenring.jpg',
    alt: 'Imagem do jogo Elden Ring',
    name: 'Elden Ring',
    info: 'Grande atualização',
    devices: '',
    description: 'Uma expansão futura para ELDEN RING, Shadow of the Erdtree, está atualmente em desenvolvimento.',
    categories: '',
    price: 'R$: 249,90',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/huntshowdown.jpg',
    alt: 'Imagem do jogo Hunt: Showdown',
    name: 'Hunt: Showdown',
    info: 'Grande atualização',
    devices: '',
    description: 'Esta nova atualização de Hunt: Showdown inclui um novo tutorial, alterações na interface do usuário, bônus individuais, novas variantes de armas e muito mais! Os Servidores de Teste estão agora AO VIVO com a Atualização 1.12!',
    categories: '',
    price: 'R$: 89,00',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/prisonarchitect.jpg',
    alt: 'Imagem do jogo Prison Architect',
    name: 'Prison Architect',
    info: 'Grande atualização',
    devices: '',
    description: 'Nova atualização The JailHouse está disponível! Juntamente com Jungle Pack que é um pacote estético que situa o teu complexo numa floresta tropical profunda e verdejante. Longe da civilização, os teus guardas vão ter de gerir os seus prisioneiros enquanto lidam com os perigos da natureza.',
    categories: '',
    price: 'R$: 57,99',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/satisfactory.jpg',
    alt: 'Imagem do jogo Satisfactory',
    name: 'Satisfactory',
    info: 'Grande atualização',
    devices: '',
    description: 'Os diagramas são a maior adição ao jogo que vem com a Atualização 7, mas lembre-se de que ainda não terminamos totalmente com eles. Para a atualização 7, isso é o que podemos compartilhar com você, e estamos ansiosos para receber seus comentários e o que você fizer com eles no acesso antecipado antes de finalizarmos o recurso em uma atualização futura.',
    categories: '',
    price: 'R$: 59,99',
    discount: '',
  },
  {
    imageUrl: '/images/atualizados/baldursgate.jpg',
    alt: 'Imagem do jogo Baldurs Gate 3',
    name: 'Baldurs Gate 3',
    info: 'Grande atualização',
    devices: '',
    description: 'A atualização #9 é nossa atualização principal final antes do lançamento em agosto de 2023, enquanto damos os retoques finais no BG3. Esta atualização inspirada pela comunidade é uma resposta direta aos seus comentários e traz alguns dos recursos e alterações mais solicitados para Baldurs Gate 3. Aumentamos o limite de nível, renovamos nosso Sistema de Reações, desbloqueamos Voar e revelamos um jogo há muito esperado classe: Paladino, juntamente com muitas outras novas adições, ajustes e correções.',
    categories: '',
    price: 'R$: 199,99',
    discount: '',
  }
];

export const indies = [
  {
    imageUrl: '/images/indies/farthestfrontier.jpg',
    alt: 'Imagem do Jogo Farthest Frontier',
    name: 'Farthest Frontier',
    releaseDate: '9/ago./2022',
    totalReviews: '11,175',
    positiveReviews: '85%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Proteja e guie seu povo para fundar uma cidade no meio do nada nos limites do mundo conhecido. Colha matérias-primas, cace, pesque e cultive para sobreviver. Produza itens para vender, consumir, equipar e lutar enquanto briga por sobrevivência contra os elementos e ameaças externas.',
    categories: ['Acesso Antecipado', 'Construção de Cidades', 'Sobrevivência', 'Estratégia'],
    price: 'R$ 57,99',
    discount: '15%',
    developer: 'Crate Entertainment',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/grimdawn.jpg',
    alt: 'Imagem do Jogo Grimdawn',
    name: 'Grimdawn',
    releaseDate: '25/fev./2016',
    totalReviews: '68,354',
    positiveReviews: '93%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Entre em um mundo de fantasia apocalíptico onde a humanidade está à beira da extinção, o ferro é mais valioso do que o ouro e a confiança é conquistada com muito esforço. Este ARPG apresenta desenvolvimento de personagem complexo, centenas de itens exclusivos, criação e missões com escolha e consequência.',
    categories: ['RPG de Ação', 'Fantasia Sombria', 'Hack and Slash', 'Saques'],
    price: 'R$ 47,49',
    discount: '75%',
    developer: 'Crate Entertainment',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/phasmophobia.jpg',
    alt: 'Imagem do Jogo Phasmophobia',
    name: 'Phasmophobia',
    releaseDate: '18/set./2020',
    totalReviews: '437,710',
    positiveReviews: '96%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Phasmophobia é um jogo de terror psicológico cooperativo online para 4 jogadores. A atividade paranormal está em ascensão e cabe a você e sua equipe usar todo o equipamento de caça fantasma à sua disposição para reunir o máximo de evidências possível.',
    categories: ['Terror', 'Cooperativo On-line', 'Multijogador', 'RV'],
    price: 'R$ 27,89',
    discount: '15%',
    developer: 'Kinetic Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/darkestdungeon2.jpg',
    alt: 'Imagem do Jogo Darkest Dungeon 2',
    name: 'Darkest Dungeon 2',
    releaseDate: '8/mai./2023',
    totalReviews: '23,458',
    positiveReviews: '85%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Darkest Dungeon II é uma aventura roguelike amaldiçoada. Monte um grupo, equipe sua carruagem e explore cenários decadentes numa última tentativa de evitar o apocalipse. Mas cuidado, pois os maiores perigos que você enfrentará podem vir de dentro...',
    categories: ['Tática por Turnos', 'Roguelite', 'Um Jogador', 'CRPG'],
    price: 'R$: 56,99',
    discount: '',
    developer: 'Red Hook Studios',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/thelongdark.jpg',
    alt: 'Imagem do Jogo The Long Dark',
    name: 'The Long Dark',
    releaseDate: '1/ago./2017',
    totalReviews: '84,193',
    positiveReviews: '91%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Luzes iluminam o céu noturno. O vento sopra impiedosamente contra as paredes finas do seu chalé de madeira. Um lobo uiva à distância. Você observa os parcos suprimentos na sua mochila e anseia pelos dias que precederam o misterioso sumiço da eletricidade. Quanto tempo você ainda sobreviverá?',
    categories: ['Sobrevivência', 'Mundo Aberto', 'Um Jogador', 'Exploração'],
    price: 'R$ 59,99',
    discount: '50%',
    developer: 'Hinterland Studio Inc.',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/hades.jpg',
    alt: 'Imagem do Jogo Hades',
    name: 'Hades',
    releaseDate: '17/set./2020',
    totalReviews: '203,704',
    positiveReviews: '98%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Desafie o deus dos mortos enquanto você batalha para sair do Submundo neste jogo roguelike dos mesmos criadores de Bastion, Transistor e Pyre.',
    categories: ['Roguelike de Ação', 'Roguelite', 'Hack and Slash', 'Souslike'],
    price: 'R$ 73,99',
    discount: '',
    developer: 'Supergiant Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/roguelegacy2.jpg',
    alt: 'Imagem do Jogo Rogue Legacy 2',
    name: 'Rogue Legacy 2',
    releaseDate: '28/abr./2022',
    totalReviews: '11,769',
    positiveReviews: '90%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Rogue Legacy 2 é o resultado da mistura de Rogue Legacy com uma sequência. Quando você morre, seus descendentes assumem seu legado. Sua filha pode ser uma Mateira Discromatópsica, e seu filho, um Chef Pacifista. De qualquer modo, um deles vai ser convocado.',
    categories: ['Ação', 'Aventura', 'Difícil', 'RPG'],
    price: 'R$ 73,99',
    discount: '',
    developer: 'Cellar Door Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/northgard.jpg',
    alt: 'Imagem do Jogo Northgard',
    name: 'Northgard',
    releaseDate: '7/mar./2018',
    totalReviews: '41,283',
    positiveReviews: '88%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Northgard é um jogo de estratégia baseado na mitologia nórdica em que você controla um clã de vikings lutando pelo controle de um misterioso continente recém-descoberto.',
    categories: ['Estratégia', 'Simulação', 'Construção de Cidades', 'Tático'],
    price: 'R$ 57,99',
    discount: '70%',
    developer: 'Shiro Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/7daystodie.jpg',
    alt: 'Imagem do Jogo 7 Days to Die',
    name: '7 Days to Die',
    releaseDate: '13/dez./2013',
    totalReviews: '173,629',
    positiveReviews: '88%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '7 Days to Die é um jogo de mundo aberto único que combina jogo de tiro em primeira pessoa, terror de sobrevivência, defesa de torre e RPG. Jogue o definitivo RPG de mundo aberto e sobrevivência zumbi que chegou primeiro. Navezgane está à sua espera!',
    categories: ['Sobrevivência', 'Zumbis', 'Mundo Aberto', 'Pós-Apocalíptico'],
    price: 'R$ 44,99',
    discount: '',
    developer: 'The Fun Pimps',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/projectzomboid.jpg',
    alt: 'Imagem do Jogo Project Zomboid',
    name: 'Project Zomboid',
    releaseDate: '8/nov./2013',
    totalReviews: '138,684',
    positiveReviews: '93%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Projeto Zomboid é o máximo em sobrevivência zumbi. Sozinho ou em MP: você saqueia, constrói, fabrica, luta, cultiva e pesca em uma luta pela sobrevivência. Um conjunto de habilidades de RPG hardcore, um mapa vasto, uma caixa de areia extremamente personalizável e um guaxinim fofo tutorial aguardam os incautos. Então, como você vai morrer? Só é preciso uma mordida..',
    categories: ['Sobrevivência', 'Zumbis', 'Mundo Aberto', 'Pós-Apocalíptico'],
    price: 'R$ 37,99',
    discount: '33%',
    developer: 'The Indie Stone',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/oxygennotincluded.jpg',
    alt: 'Imagem do Jogo Oxygen Not Included',
    name: 'Oxygen Not Included',
    releaseDate: '30/jul./2019',
    totalReviews: '90759',
    positiveReviews: '96%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Oxygen Not Included é um jogo de simulação de colônia espacial. Nas profundezas de uma rocha espacial alienígena, sua equipe diligente precisará dominar a ciência, superar novas formas de vida estranhas e aproveitar a incrível tecnologia espacial para sobreviver e, possivelmente, prosperar.',
    categories: ['Estratégia', 'Simulador de Colônias', 'Sobrevivência', 'Construção'],
    price: 'R$ 45,99',
    discount: '',
    developer: 'Klei Entertainment',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/vrising.jpg',
    alt: 'Imagem do Jogo V Rising',
    name: 'V Rising',
    releaseDate: '17/mai./2022',
    totalReviews: '53,104',
    positiveReviews: '88%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Acorde como um vampiro após séculos de sono profundo. Evite o sol enquanto você vai atrás de sangue para recuperar sua força. Reconstrua seu castelo e converta humanos em seus servos leais durante a sua missão para criar um império vampiro. Trave uma guerra nesse mundo de conflitos.',
    categories: ['Sobrevivência', 'Acesso Antecipado', 'Mundo Aberto', 'Multijogador'],
    price: 'R$ 37,99',
    discount: '20%',
    developer: 'Stunlock Studios',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/acrosstheobelisk.jpg',
    alt: 'Imagem do Jogo Across the Obelisk',
    name: 'Across the Obelisk',
    releaseDate: '8/abr./2021',
    totalReviews: '5,956',
    positiveReviews: '92%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Across the Obelisk é um roguelite de construção de deck de RPG cooperativo. Jogue sozinho ou com seus amigos, escolha seus heróis, desbloqueie itens e cartas, crie seu baralho e enfrente inimigos poderosos em combates táticos profundos. Você teria coragem de atravessar o obelisco?',
    categories: ['Cooperativo', 'Cartas', 'RPG', 'Estratégia'],
    price: 'R$ 66,99',
    discount: '',
    developer: 'Dreamsite Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/graveyardkeeper.jpg',
    alt: 'Imagem do Jogo Graveyard Keeper',
    name: 'Graveyard Keeper',
    releaseDate: '15/ago./2018',
    totalReviews: '24,711',
    positiveReviews: '86%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: 'Dos criadores de Punch Club, chegou Graveyard Keeper, o simulador de gerenciamento de cemitérios medievais mais impreciso de todos os tempos.',
    categories: ['Medieval', 'Aventura', 'RPG', 'Simulação'],
    price: 'R$ 59,99',
    discount: '65%',
    developer: 'Lazy Bear Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/slaythespire.jpg',
    alt: 'Imagem do Jogo Slay the Spire',
    name: 'Slay the Spire',
    releaseDate: '23/jan./2019',
    totalReviews: '109,319',
    positiveReviews: '97%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Nós combinamos jogos de carta com roguelike para fazer o melhor deckbuilder single player que pudemos. Monte um deck único, encontre criaturas bizarras, descubra relíquias de imenso poder, e Destrua o Pináculo(Slay The Spire)!',
    categories: ['Roguelike', 'Cartas', 'RPG', 'Um Jogador'],
    price: 'R$ 47,49',
    discount: '',
    developer: 'Mega Crit Games',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
  {
    imageUrl: '/images/indies/hellcard.jpg',
    alt: 'Imagem do Jogo HELLCARD',
    name: 'HELLCARD',
    releaseDate: '16/fev./2023',
    totalReviews: '780',
    positiveReviews: '86%',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Hellcard é um jogo único de construção cooperativa de deck roguelike. Desça nas masmorras de papel por conta própria, recrute AI companheiros ou junte-se aos lobbies de outros jogadores em batalhas táticas rápidas de cartas contra os exércitos das trevas e o Arquidemônio!',
    categories: ['Acesso Antecipado', 'Cartas', 'RPG', 'Cooperativo'],
    price: 'R$ 32,39',
    discount: '',
    developer: 'Thing Trunk',
    friends: ['/images/friends/friend1.jpg', '/images/friends/friend2.jpg', '/images/friends/friend3.jpg'],
  },
];

export const preferencias = [
  {
    imageUrl: '/images/preferencias/ark.jpg',
    alt: '',
    name: 'Ark Survival Evolved',
    info: 'Jogo Base',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Multijogador', 'Dinossauros'],
    price: 'R$ 37,99',
    discount: '',
    developer: 'Cellar Door Games',
  },
  {
    imageUrl: '/images/preferencias/raft.jpg',
    alt: '',
    name: 'Raft',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Multijogador', 'Construção'],
    price: 'R$ 36,99',
    discount: '',
    developer: 'Shiro Games',
  },
  {
    imageUrl: '/images/preferencias/dontstarvetogether.jpg',
    alt: '',
    name: 'Don\'t Starve Together',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Multijogador', 'Pós-Apocalíptico'],
    price: 'R$ 27,99',
    discount: '',
    developer: 'The Fun Pimps',
  },
  {
    imageUrl: '/images/preferencias/terraria.jpg',
    alt: '',
    name: 'Terraria',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo', 'Exploração'],
    price: 'R$ 19,99',
    discount: '',
    developer: 'The Indie Stone',
  },
  {
    imageUrl: '/images/preferencias/rust.jpg',
    alt: '',
    name: 'Rust',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Multijogador', 'Construção'],
    price: 'R$ 103,49',
    discount: '',
    developer: 'Klei Entertainment',
  },
  {
    imageUrl: '/images/preferencias/greenhell.jpg',
    alt: '',
    name: 'GreenHell',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Um Jogador', 'Ação'],
    price: 'R$ 51,79',
    discount: '',
    developer: 'Stunlock Studios',
  },
  {
    imageUrl: '/images/preferencias/conanexiles.jpg',
    alt: '',
    name: 'Conan Exiles',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Multijogador', 'Ação'],
    price: 'R$ 99,49',
    discount: '',
    developer: 'Dreamsite Games',
  },
  {
    imageUrl: '/images/preferencias/grounded.jpg',
    alt: '',
    name: 'Grounded',
    info: 'Jogo Base',
    devices: [<AiFillWindows />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo', 'Estratégia'],
    price: 'R$ 197,72',
    discount: '',
    developer: 'Dreamsite Games',
  },
];

export const displayBestSellers = [
  {
    imageUrl: '/images/display/residentevil1440.jpg',
    alt: '',
    name: 'Resident Evil 4',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
    price: 'R$ 249,00',
    discount: '45%',
  },
  {
    imageUrl: '/images/display/fifa1440.jpg',
    alt: '',
    name: 'EA SPORTS FIFA 23',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
    price: 'R$ 299,00',
    discount: '',
  },
  {
    imageUrl: '/images/display/cod1440.jpg',
    alt: '',
    name: 'Call of Duty: Modern Warfare II',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
    price: 'R$ 299,90',
    discount: '',
  },
  {
    imageUrl: '/images/display/deadcells1440.jpg',
    alt: '',
    name: 'Dead Cells',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
    price: 'R$ 47,49',
    discount: '',
  },
  {
    imageUrl: '/images/display/destiny1440.jpg',
    alt: '',
    name: 'Destiny 2',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
    price: 'Gratuito',
    discount: '',
  },
  // {
  //   imageUrl: '/images/display/reddead1440.jpg',
  //   name: 'Red Dead Redemption 2',
  //   price: 'R$ 299,90',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '67%',
  //   categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
  // },
  // {
  //   imageUrl: '/images/display/hogwartslegacy1440.jpg',
  //   name: 'Hogwarts Legacy',
  //   price: 'R$ 249,99',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '',
  //   categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
  // },
  // {
  //   imageUrl: '/images/display/monsterhunter1440.jpg',
  //   name: 'MONSTER HUNTER RISE',
  //   price: 'R$ 139,90',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '50%',
  //   categories: ['Sobrevivência em Mundo Aberto', 'Sobrevivência', 'Cooperativo'],
  // },
];

export const displayMostPlayeds = [
  {
    imageUrl: '/images/display/rainbow1440.jpg',
    alt: '',
    name: 'Tom Clancy\'s Rainbow Six® Siege    ',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Ação', 'Sobrevivência'],
    price: 'R$ 59,99',
    discount: '',
  },
  {
    imageUrl: '/images/display/apex1440.jpg',
    alt: '',
    name: 'Apex Legends',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Ação', 'Sobrevivência'],
    price: 'Gratuito',
    discount: '',
  },
  {
    imageUrl: '/images/display/rocketleague1440.jpg',
    alt: '',
    name: 'Rocket League',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Ação', 'Sobrevivência'],
    price: 'R$ 29,99',
    discount: '',
  },
  {
    imageUrl: '/images/display/destiny1440.jpg',
    alt: '',
    name: 'Destiny 2',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Ação', 'Sobrevivência'],
    price: 'Gratuito',
    discount: '',
  },
  {
    imageUrl: '/images/display/gtav1440.jpg',
    alt: '',
    name: 'Grand Theft Auto V',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: ['Ação', 'Sobrevivência'],
    price: 'R$ 108,89',
    discount: '65%',
  },
  // {
  //   imageUrl: '/images/display/pubg1440.jpg',
  //   name: 'PUBG: BATTLEGROUNDS',
  //   price: 'Gratuito',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '',
  //   categories: ['Ação', 'Sobrevivência']  
  // },
  // {
  //   imageUrl: '/images/display/rust1440.jpg',
  //   name: 'Rust',
  //   price: 'R$ 103,49',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '',
  //   categories: ['Ação', 'Sobrevivência']  },
  // {
  //   imageUrl: '/images/display/forza1440.jpg',
  //   name: 'Forza Horizon 5',
  //   price: 'R$ 249,00',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '',
  //   categories: ['Ação', 'Sobrevivência']  
  // },
];

export const displaySales = [
  {
    imageUrl: '/images/display/ori1440.jpg',
    alt: '',
    name: 'Ori and the Will of the Wisps',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: '',
    price: 'R$ 129,00',
    discount: '80%',
  },
  {
    imageUrl: '/images/display/dmc1440.jpg',
    alt: '',
    name: 'Devil May Cry 5',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: '',
    price: 'R$ 99,90',
    discount: '67%',
  },
  {
    imageUrl: '/images/display/resident1440.jpg',
    alt: '',
    name: 'Resident Evil 2',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: '',
    price: 'R$ 139,90',
    discount: '75%',
  },
  {
    imageUrl: '/images/display/deadbydaylight1440.jpg',
    alt: '',
    name: 'Dead by Daylight',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: '',
    price: 'R$ 49,99',
    discount: '60%',
  },
  {
    imageUrl: '/images/display/totalwar1440.jpg',
    alt: '',
    name: 'Total War Warhammer III',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '',
    categories: '',
    price: 'R$ 252,00',
    discount: '33%',
  },
  // {
  //   imageUrl: '/images/display/battlefield1440.jpg',
  //   name: 'Battlefield 2042',
  //   price: 'R$ 249,00',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '70%',
  //   categories: '',
  // },
  // {
  //   imageUrl: '/images/display/nba1440.jpg',
  //   name: 'NBA 2K23',
  //   price: 'R$ 499,50',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '60%',
  //   categories: '',
  // },
  // {
  //   imageUrl: '/images/display/detroit1440.jpg',
  //   name: 'Detroit: Become Human',
  //   price: 'R$ 134,99',
  //   devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
  //   discount: '50%',
  //   categories: '',
  // },
];

export const avaliados = [
  {
    imageUrl: '/images/avaliados/witcher3.jpg',
    alt: '',
    name: 'The Witcher 3: Wild Hunt - Complete Edition',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Você é Geralt de Rívia, mercenário matador de monstros. Você está em um continente devastado pela guerra e infestado de monstros para você explorar à vontade. Sua tarefa é encontrar Ciri, a Criança da Profecia — uma arma viva que pode alterar a forma do mundo. Essa edição inclui todos os conteúdos adicionais – novas armas, armaduras, trajes de companheiros, novo modo de jogo e missões secundárias.',
    categories: '',
    price: 'R$ 99,99',
    discount: '',
    totalReview: '710,000',
    positiveReview: 'Positivas: (680.000+)',
    negativeReview: 'Negativas: (28,000+)',
    developer: 'CD PROJEKT RED',
  },
  {
    imageUrl: '/images/avaliados/skyrim.jpg',
    alt: '',
    name: 'The Elder Scrolls V: Skyrim Special Edition',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: 'Vencedor de mais de 200 prêmios de Jogo do Ano, Skyrim Special Edition dá vida à fantasia épica em detalhes impressionantes. A Special Edition inclui o jogo aclamado pela crítica e extras com características novas como arte e efeitos remasterizados, raios crepusculares volumétricos, profundidade de campo dinâmica, reflexos de objetos e muito mais. Skyrim Special Edition também traz a força total de mods para consoles. Novas missões, ambientes, personagens, diálogos, armaduras, armas e muito mais. Com mods, não há limites para a sua experiência.',
    categories: '',
    price: 'R$ 149,00',
    discount: '',
    totalReview: '245,000',
    positiveReview: 'Positivas: (225,000+)',
    negativeReview: 'Negativas: (20,000+)',
    developer: 'Bethesda',
  },
  {
    imageUrl: '/images/avaliados/halflife2.jpg',
    alt: '',
    name: 'Half-Life 2',
    info: '',
    devices: [<AiFillWindows />, <FaPlaystation />, <FaXbox />],
    description: '1998. HALF-LIFE manda um choque na indústria de jogos com sua combinação de ação batedora e história contínua e imersiva. O título de estreia da Valve ganha mais de 50 prêmios de jogo do ano no seu caminho a ser denominado o "Melhor jogo de PC de todos os tempos".',
    categories: '',
    price: 'R$ 32,99',
    discount: '',
    totalReview: '160,000',
    positiveReview: 'Positivas: (155,000+)',
    negativeReview: 'Negativas: (4,000+)',
    developer: 'Valve',
  },
];

export const curiosidadesObjetos = [
  {
    imageUrl: ["/images/icons/facebook.png", "/images/icons/instagram_box.png", "/images/icons/twitter.png"],
    text: "Você sabia? A Games Emporium está no mercado desde 2007 te trazendo o melhor que existe no mundo dos jogos. Possuímos  promoções diárias e ofertas imperdíveis. Recomende o nosso site!"
  }
];

export default function Constants() {
  return (
    <>
    </>
  )
}